Repository IvanArana/WristWonders, pull requests merged in 2023-07, with the labels that each got.

#11 Integracion de Feature/ID54-Vista_AgregarProductos
  src/App.js
  src/components/Confirmacion.js
  src/css/Admin.css
  src/modules/Admin.js
  src/modules/AgregarProductos.js
  src/modules/CategoriasAD.js
  src/modules/Marcas.js
  src/modules/Materiales.js
  src/modules/ProductosAD.js
  src/modules/TipoReloj.js
Labels: front

#12 Integracion de id-43 detalles de productos
  src/App.js
  src/css/Login.css
  src/modules/DetallesProductos.js
  src/modules/ProductosMarca.js
  src/modules/ProductosMaterial.js
  src/modules/ProductosTipo.js
Labels: front

#14 Integracion Feature/id 48 49 50/carrito&datos user
  package-lock.json
  package.json
  server/index.js
  server/node_modules/.package-lock.json
  server/package-lock.json
  server/package.json
  src/App.js
  src/components/Card.js
  src/css/Login.css
  src/modules/Carrito.js
  src/modules/DatosUser.js
Labels: front

#15 Feature/id 32/pantalla principal usuario
  server/index.js
Labels: back

#16 Integracion de feature/id-30/loign_y_registro más reestructuración del back end
  .idea/.gitignore
  .idea/WristWonders.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  server/.env
  server/controllers/productosController.js
  server/controllers/usuariosController.js
  server/db.js
  server/index.js
  server/node_modules/.package-lock.json
  server/node_modules/dotenv/CHANGELOG.md
  server/node_modules/dotenv/LICENSE
  server/node_modules/dotenv/README-es.md
  server/node_modules/dotenv/README.md
  server/node_modules/dotenv/config.d.ts
  server/node_modules/dotenv/config.js
  server/node_modules/dotenv/lib/cli-options.js
  server/node_modules/dotenv/lib/env-options.js
  server/node_modules/dotenv/lib/main.d.ts
  server/node_modules/dotenv/lib/main.js
  server/node_modules/dotenv/package.json
  server/package-lock.json
  server/package.json
Labels: back

#17 Filter pruduct & crud, register validation fix
  server/controllers/productosController.js
  server/controllers/usuariosController.js
Labels: back

#20 integracion de funcionalidades de ID 70 y 72
  src/App.js
  src/modules/DetallesProductos.js
  src/modules/User.js
Labels: integration of functionalities

#21 Feature/eslint
  .eslintignore
  .eslintrc.js
  .vscode/settings.json
  package-lock.json
  package.json
  server/controllers/productosController.js
  server/controllers/usuariosController.js
  server/index.js
  src/App.js
  src/components/Confirmacion.js
  src/components/Footer.js
  src/components/LoginForm.js
  src/components/Navbar.js
  src/components/ProductosAD.js
  src/components/RegisterForm.js
  src/components/Sidebar.js
  src/index.js
  src/modules/Admin.js
  src/modules/AgregarProductos.js
  src/modules/Carrito.js
  src/modules/CategoriaUser.js
  src/modules/CategoriasAD.js
  src/modules/DatosUser.js
  src/modules/DetallesProductos.js
  src/modules/Login.js
  src/modules/Marcas.js
  src/modules/Materiales.js
  src/modules/ProductosAD.js
  src/modules/ProductosMarca.js
  src/modules/ProductosMaterial.js
  src/modules/ProductosTipo.js
  src/modules/Registro.js
  src/modules/TipoReloj.js
  src/modules/User.js
Labels: feature

#23 merge dev
  server/controllers/productosController.js
  server/controllers/usuariosController.js
  server/db.js
  src/modules/AgregarProductos.js
  src/modules/Carrito.js
  src/modules/CategoriaUser.js
  src/modules/Marcas.js
  src/modules/Materiales.js
  src/modules/ProductosMarca.js
  src/modules/ProductosMaterial.js
  src/modules/ProductosTipo.js
  src/modules/Registro.js
  src/modules/TipoReloj.js
Labels: fix

#24 Test/deploy
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/main.yml
  firebase.json
  public/404.html
Labels: feature

#26 configuracion eslint
  .eslintrc.js
  server/controllers/productosController.js
  server/controllers/usuariosController.js
  server/db.js
  src/App.test.js
  src/modules/CategoriaUser.js
  src/reportWebVitals.js
Labels: fix

#28 Fix/eslint
  .eslintrc.js
Labels: fix
